version: "3.8"

services:
  backend:
    build:
      context: ./backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - backend/.env
  
  db:
    image: postgres:14.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - backend/.env
  
  frontend: 
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
    container_name: react_frontend
  
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend 
    container_name: nginx

volumes:
  react_build:

  
