# Generated by Django 3.2.7 on 2022-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(choices=[('SPORT', 'SPORT'), ('DIET', 'DIET'), ('HEALTH', 'HEALTH'), ('LIFESTYLE', 'LIFESTYLE')], default='SPORT', max_length=15),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
