# Generated by Django 3.2.7 on 2022-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short',
            field=models.TextField(default='Kapitan Koks', max_length=250),
            preserve_default=False,
        ),
    ]
